---
# tasks file for role_bi_packages_minimum
- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml" # For OpenSuSE Leap ansible_distribution_major_version is NA
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
  tags:
    - always

- name: Include os independent variables.
  include_vars: "vars/main.yml"

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
  tags: [ never, debug ]

- name: Install role_bi_packages_minimum
  include: 01-packages.yml

- name: Configure role_bi_packages_minimum
  include: 02-configure.yml

